CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  cpf TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('ADMIN', 'USER')),
  is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS service_orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  location_text TEXT,
  expected_start TIMESTAMPTZ NOT NULL,
  expected_duration_hours INTEGER NOT NULL CHECK (expected_duration_hours > 0),
  status TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'CLOSED')),
  created_by INTEGER NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  closed_at TIMESTAMPTZ,
  closed_by INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS service_order_assignments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_order_id INTEGER NOT NULL REFERENCES service_orders(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(service_order_id, user_id)
);

CREATE TABLE IF NOT EXISTS times_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('IN', 'OUT')),
  occurred_at TIMESTAMPTZ NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  note TEXT,
  adjusted_by INTEGER REFERENCES users(id),
  adjusted_at TIMESTAMPTZ,
  adjustment_note TEXT,
  source_alert_id INTEGER,
  service_order_id INTEGER REFERENCES service_orders(id)
);

CREATE TABLE IF NOT EXISTS alerts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  time_in_entry_id INTEGER REFERENCES times_entries(id) ON DELETE SET NULL,
  severity INTEGER NOT NULL DEFAULT 1,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at TIMESTAMPTZ,
  resolved_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  resolution_note TEXT
);

CREATE INDEX IF NOT EXISTS idx_times_entries_user_id ON times_entries (user_id);
CREATE INDEX IF NOT EXISTS idx_times_entries_occurred_at ON times_entries (occurred_at);
CREATE INDEX IF NOT EXISTS idx_times_entries_so ON times_entries (service_order_id);

CREATE INDEX IF NOT EXISTS idx_alerts_user_id ON alerts(user_id);
CREATE INDEX IF NOT EXISTS idx_alerts_created_at ON alerts(created_at);
CREATE INDEX IF NOT EXISTS idx_alerts_resolved_at ON alerts(resolved_at);

CREATE INDEX IF NOT EXISTS idx_so_status ON service_orders(status);
CREATE INDEX IF NOT EXISTS idx_so_assign_user ON service_order_assignments(user_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_alerts_open_unique
ON alerts(type, user_id, time_in_entry_id)
WHERE resolved_at IS NULL;
